"""
Cowrie Honeypot Log Adapter.
Streams and parses JSON event logs generated by a Cowrie SSH/Telnet honeypot instance,
normalizing authentication attempts, command executions, and file downloads into the Common Alert Schema.
"""

import json
import uuid
from pathlib import Path
from datetime import datetime, timezone
from typing import Optional, Dict, Any

from sources.base_source import BaseSource
from sources.event_queue import UnifiedEventQueue
from engine.models import Alert, Severity, AssetTier


class CowrieAdapter(BaseSource):
    def __init__(
        self,
        log_file_path: str = "data/cowrie.json",
        event_queue: Optional[UnifiedEventQueue] = None
    ):
        super().__init__(name="CowrieAdapter", event_queue=event_queue)
        self.log_file = Path(log_file_path)

    def normalize_cowrie_event(self, entry: Dict[str, Any]) -> Optional[Alert]:
        event_id = entry.get("eventid", "")
        src_ip = entry.get("src_ip", "unknown")
        user = entry.get("username", "root")
        password = entry.get("password", "")
        cmd = entry.get("input", "")
        ts_raw = entry.get("timestamp")

        if ts_raw:
            try:
                ts = datetime.fromisoformat(ts_raw.replace("Z", "+00:00"))
            except Exception:
                ts = datetime.now(timezone.utc)
        else:
            ts = datetime.now(timezone.utc)

        if "login.failed" in event_id:
            rule_name = f"Honeypot: SSH Login Failed ({user}:{password})"
            event_type = "HONEYPOT_AUTH_FAILED"
            sev = Severity.MEDIUM
            tactic = "Credential Access"
            tech_id = "T1110"
            tech_name = "Brute Force"
        elif "login.success" in event_id:
            rule_name = f"Honeypot: SSH Login Accepted ({user})"
            event_type = "HONEYPOT_AUTH_SUCCESS"
            sev = Severity.HIGH
            tactic = "Initial Access"
            tech_id = "T1078"
            tech_name = "Valid Accounts"
        elif "command.input" in event_id:
            rule_name = f"Honeypot: Attacker Command Executed ({cmd[:40]})"
            event_type = "HONEYPOT_COMMAND"
            sev = Severity.HIGH
            tactic = "Execution"
            tech_id = "T1059"
            tech_name = "Command and Scripting Interpreter"
        else:
            rule_name = f"Honeypot: Deception Event ({event_id})"
            event_type = "HONEYPOT_GENERIC"
            sev = Severity.LOW
            tactic = "Reconnaissance"
            tech_id = "T1046"
            tech_name = "Network Service Discovery"

        return Alert(
            alert_id=f"COWRIE-{uuid.uuid4().hex[:8].upper()}",
            timestamp=ts,
            rule_name=rule_name,
            severity=sev,
            source="cowrie",
            type=event_type,
            host="CLOUD-DECOY-SSH",
            user=user,
            src_ip=src_ip,
            hostname="CLOUD-DECOY-SSH",
            username=user,
            source_ip=src_ip,
            command_line=cmd or password,
            mitre_tactic=tactic,
            mitre_technique_id=tech_id,
            mitre_technique_name=tech_name,
            asset_tier=AssetTier.TIER_3,
            asset_criticality_score=2.0,
            business_unit="Threat Deception Network",
            raw_payload=entry
        )

    async def start(self) -> None:
        self._running = True
        if self.log_file.exists():
            with open(self.log_file, "r", encoding="utf-8") as f:
                for line in f:
                    if line.strip():
                        try:
                            data = json.loads(line)
                            alert = self.normalize_cowrie_event(data)
                            if alert:
                                await self.emit(alert)
                        except Exception:
                            pass

    async def stop(self) -> None:
        self._running = False

